server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  product:
    service:
      url: http://localhost:8082/api/products/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  resilience4j:
  circuitbreaker:
    instances:
      productServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      productServiceRetry:
        maxAttempts: 3
        waitDuration: 2s

  mail:
    host: smtp.gmail.com
    port: 587
    username: faisallatif8979@gmail.com
    password: okdhxboedqpqtgst
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
